name: the_qa
description: "The QA - A Questionare community."
publish_to: 'none' 
version: 1.0.0+6

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  firebase_database: ^12.1.1
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/


